version: '3.8'

services:
  api:
    build:
      context: ./cloud-printer-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cloud_printer
      - PORT=3000
    volumes:
      - ./cloud-printer-api:/app
      - /app/node_modules
    depends_on:
      - db

  client:
    build:
      context: ./cloud-printer-client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./cloud-printer-client:/app
      - /app/node_modules

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cloud_printer
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 